name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Step
        run: echo "Building the project in ${{ job.environment }} environment..."

  test:
    runs-on: ubuntu-latest
    needs: build
    environment: Qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Running tests in ${{ job.environment }} environment..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: Stag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Step
        run: echo "Deploying application in ${{ job.environment }} environment..."
