name: Simple Multi Env Pipeline

on:
  push:
    branches: [ main ]

jobs:
  dev:
    runs-on: ubuntu-latest 
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to DEV"

  test:
    runs-on: ubuntu-latest
    needs: dev
    environment: test
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to TEST"

  prod:
    runs-on: ubuntu-latest
    needs: test
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to PROD"
